watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: false
      acrylic: true
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 24
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["home", "media", "systray", "apps"]
      center: ["taskbar"]
      right:
        [
          "launchpad",
          "clock",
          "cpu",
          "memory",
          "disk",
          "bin",
          "volume",
          "power_menu",
        ]
widgets:
  ### HOME WIDGET ###
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Downloads", path: "~\\Downloads" }
        - { title: "Coding", path: "C:\\Coding" }
      system_menu: false
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "small"
      border_color: "#7aa2f7"
      alignment: "left"
      offset_left: 4
      offset_top: 0
  ### MEDIA WIDGET ###
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: "{title}"
      hide_empty: true
      callbacks:
        on_left: "exec cmd /c start spotify://queue"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      max_field_size:
        label: 20
        label_alt: 20
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 80
      thumbnail_padding: 10
      thumbnail_corner_radius: 10
      scrolling_label:
        enabled: true
        update_interval_ms: 33
        style: "left" # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 1
        # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04d"
      media_menu:
        blur: false
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 0
        offset_left: 0
        thumbnail_corner_radius: 6
        thumbnail_size: 200
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\uf04b"
        pause: "\uf04d"
        prev_track: "\uf048"
        next_track: "\ue893"
  ### SYSTRAY WIDGET ###
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb81\udf2e"
      label_expanded: "\udb81\udf34"
      label_position: "center"
      icon_size: 20
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      btn_shadow:
        enabled: false
        color: "black"
        radius: 10
        offset: [20, 20]
  ### APPLICATIONS WIDGET ###
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - {
            icon: "C:\\Users\\juanm\\.config\\yasb\\launchpad\\icons\\visual_studio_code_1753384298668.png",
            launch: "C:\\Users\\juanm\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Visual Studio Code\\Visual Studio Code.lnk",
          } # open vscode
        - {
            icon: "C:\\Users\\juanm\\.config\\yasb\\launchpad\\icons\\whatsapp_1753385430813.png",
            launch: "explorer.exe shell:AppsFolder\\5319275A.WhatsAppDesktop_cv1g1gvanyjgm!App",
          } # open whatsapp
        - {
            icon: "C:\\Users\\juanm\\.config\\yasb\\launchpad\\icons\\brave_1753823021212.png",
            launch: "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe",
          } # open brave explorer
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 0
        offset: [1, 1]
  ### TASKBAR WIDGET ###
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 26
      animation:
        enabled: true
        duration: 200
        type: "fadeInOut"
      title_label:
        enabled: false
        show: "focused"
        min_length: 10
        max_length: 30
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  ### LAUNCHPAD WIDGET ###
  launchpad:
    type: "yasb.launchpad.LaunchpadWidget"
    options:
      label: "<span>\udb81\udf26</span>"
      search_placeholder: "Search for apps..."
      app_icon_size: 80
      window:
        fullscreen: false
        width: 800
        height: 500
        overlay_block: true
      window_style:
        enable_blur: true
        round_corners: true
        round_corners_type: "normal"
      window_animation:
        fade_in_duration: 200
        fade_out_duration: 200
      callbacks:
        on_left: "toggle_launchpad"
      app_title_shadow:
        enabled: true
        color: "#00000090"
        offset: [1, 1]
        radius: 2
      app_icon_shadow:
        enabled: true
        color: "#00000090"
        offset: [0, 2]
        radius: 8
  ### CLOCK WIDGET ###
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span>{%H:%M}"
      label_alt: "<span>\uf017</span>{%A, %B %d. %Y %H:%M}"
      locale: "es_ES.UTF-8"
      timezones: []
      calendar:
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        offset_top: 0
  ### CPU WIDGET ###
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf4bc</span> {info[cpu_percent]}"
      update_interval: 2000
      histogram_num_columns: 8
      callbacks:
        on_left: "exec cmd /c start taskmgr"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
  ### MEMORY WIDGET ###
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span>{virtual_mem_outof}"
      label_alt: "<span>\uf4bc</span>{virtual_mem_outof}"
      update_interval: 2000
      callbacks:
        on_right: "exec cmd /c Taskmgr"
        on_left: "do_nothing"
  ### DISK WIDGET ###
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\uf473</span> Disk"
      label_alt: "<span>\uf473</span>"
      group_label:
        volume_labels:
          [
            "A",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",
          ]
        show_label_name: false
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        offset_top: 0
      callbacks:
        on_left: "toggle_group"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 10
      max_length: 40
      max_length_ellipsis: "..."
      monitor_exclusive: true
  ### RECYCLE BIN WIDGET ###
  bin:
    type: "yasb.recycle_bin.RecycleBinWidget"
    options:
      label: "<span>{icon}</span> Items {items_count}"
      label_alt: "Items {items_count}"
      callbacks:
        on_left: "exec cmd /c start shell:RecycleBinFolder"
  ### VOLUME WIDGET ###
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        direction: "down"
        offset_top: 0
      callbacks:
        on_right: "toggle_mute"
  ### POWER MENU ###
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 3
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
